### ISSUE TITLE
Same problem on Section 3

### ISSUE THREAD

**Issue by bbardakk** [FatimahHA/AI-for-healthcare---Project-2-#1]
Hi Fatimah,

I saw your question on udacity about index error (https://knowledge.udacity.com/questions/318841). 

Did you solve this problem?

Thanks

**Comment by FatimahHA** [comment]
Hello,

Unfortunately, I still have the same problem and I'm not able to know the
reason.

Please if you figure out how to solve it, let me know.

Thanks.
